name: 'Update release assets'
description: 'Update Release.'
author: 'Nivaes'
inputs:
  tag_name:
    description: "Gives a tag name. Defaults to github.ref_name"
    required: true
    default: ${{ github.ref_name }}
  files:
    description: "Newline-delimited list of path globs for asset files to upload"
    required: true
runs:
  using: "composite"
  steps:     
    - name: Update release 
      id: run
      shell: bash
      run: |
        ASSETS=$(gh release view ${{ inputs.tag_name }} --json assets -q '.assets[].name')

        for ID in $ASSETS; do
          echo "Deleting asset $ID"
          gh release delete-asset "${{ inputs.tag_name }}" "$ID" --yes
        done

        ls *
        gh release upload "${{ inputs.tag_name }}" * --clobber
        # gh release upload "${{ inputs.tag_name }}" "${{ inputs.files }}" --clobber

branding:
  icon: 'tag'
  color: 'gray-dark'
